### ISSUE TITLE
Discussion: Donations

### ISSUE THREAD

**Issue by Razzeee** [xbmc/kodi-tv#114]
The donation page was way more prominent in the old design - do we want it like that again? Can we somehow enable this?

**Comment by pkscout** [comment]
At this point we are kind of out of slots on the main menu. At least unless we define a custom screen width for responsiveness, get rid of the social icons, or really cram up the main menu.  Here's a screenshot of the menu right now at the last moment before it hits the trigger point that collapses the main menu into fewer items with a **More** menu.

<img width="1141" alt="Screen Shot 2021-03-26 at 12 03 57 PM" src="https://user-images.githubusercontent.com/1402018/112697509-c680cd80-8e2b-11eb-826b-d8af0c435a70.png">

We could opt to call that menu grouping something else (like Donate). In English at least, Donate and Contribute mean almost the same thing.  It's hard trying to group the ideas of "contribute to the work" with "give us money" and "buy stuff from us." But I didn't see anything else we could group together to get the main menu under control.

Definitely open to ideas. The main menu is all defined in a big object in the header file, so it isn't all that hard to move stuff around.

**Comment by Razzeee** [comment]
Maybe another icon next to the social icons, same style but money icon + highlight color? (in addition to the menu entry)

**Comment by pkscout** [comment]
Here are some screenshots of what that might look like.  I had to compress the spacing in the main menu some to get things to look OK at the break points, but I'm not sure you can really tell unless you are doing an A/B comparison between the two spacing amounts. There's probably no more room for another icon, so if we add a social or want to add another special icon, we would have to rethink the main menu a bit.

<img width="1505" alt="Screen Shot 2021-03-27 at 9 28 51 AM" src="https://user-images.githubusercontent.com/1402018/112732629-21bfc800-8edf-11eb-8fca-b31dfdba844c.png">

<img width="1136" alt="Screen Shot 2021-03-27 at 9 29 03 AM" src="https://user-images.githubusercontent.com/1402018/112732631-24bab880-8edf-11eb-9ba1-a4cdcc0653b3.png">

<img width="880" alt="Screen Shot 2021-03-27 at 9 29 17 AM" src="https://user-images.githubusercontent.com/1402018/112732634-284e3f80-8edf-11eb-942a-a2e6f2a6641e.png">

<img width="686" alt="Screen Shot 2021-03-27 at 9 29 27 AM" src="https://user-images.githubusercontent.com/1402018/112732635-297f6c80-8edf-11eb-8cb9-e66e44df259b.png">

**Comment by Razzeee** [comment]
Which icon are you using in these?

I think I like it, but I would like to hear from @keithah and @yol or other people in the team

**Comment by pkscout** [comment]
I'm using one of the Hero Icons because it was quick for the mockup.  We might be able to find a better stylistic match somewhere else.  For instance, I'm not sure how I feel about the border on it. But here's a look with the colors reversed.

<img width="1505" alt="Screen Shot 2021-03-27 at 9 45 28 AM" src="https://user-images.githubusercontent.com/1402018/112732968-461ca400-8ee1-11eb-9f03-467a9099d047.png">

**Comment by Razzeee** [comment]
https://feathericons.com/?query=money
would be matching the other icons used there. Not a fan of the border, but I think it might work without that and with the blue background.

**Comment by yol** [comment]
Personally, I think that the social icons (FB, Twitter, YT) in the header are not that important. It's not like we post a lot of content there. RSS doesn't need to be that prominent since it's in the <link> tags anyway and it wouldn't hurt if you had to, e.g., scroll to the footer to find it. GitHub is the only one that I feel is worth the visual clutter to be honest. I'd rather see a "Donate" button with Donate spelt out even if it means other stuff has to be dropped from the menu or regrouped. I'm not sure if the "$" icon works in this context.

In the past, we wanted to make donating obvious and easy - also cf. https://www.videolan.org/

**Comment by pkscout** [comment]
Making the social icons optional does provide some new opportunities.  Here are some screenshots where we have more main menu items and sacrifice the social icons as screen real estate changes. This is a much simpler menu setup too because we aren't collapsing some of the menus into a **More** item.  In this case I put the *Working on Kodi* link in the **Help** menu (and renamed that menu to **Help** both to get back some space and make it more inclusive of getting and giving help).

Full screen:
<img width="1505" alt="Screen Shot 2021-03-28 at 9 57 11 AM" src="https://user-images.githubusercontent.com/1402018/112766263-9f053e80-8fac-11eb-92c0-e67a4f8957b4.png">

Full screen right before breakpoint:
<img width="1136" alt="Screen Shot 2021-03-28 at 9 57 22 AM" src="https://user-images.githubusercontent.com/1402018/112766282-b7755900-8fac-11eb-8796-b7154a3902c3.png">

Medium screen:
<img width="1131" alt="Screen Shot 2021-03-28 at 9 57 34 AM" src="https://user-images.githubusercontent.com/1402018/112766291-c4924800-8fac-11eb-8c13-73259399ff2e.png">

Medium screen right before breakpoint:
<img width="881" alt="Screen Shot 2021-03-28 at 9 57 41 AM" src="https://user-images.githubusercontent.com/1402018/112766297-cfe57380-8fac-11eb-9fc8-d07a2b5b3141.png">

Mobile:
<img width="686" alt="Screen Shot 2021-03-28 at 9 57 49 AM" src="https://user-images.githubusercontent.com/1402018/112766302-d542be00-8fac-11eb-9ad1-6abc34fc8498.png">

**Comment by keithah** [comment]
Love this! Agreed with donate I stead of social. Make Donate a diff background would be great so it stands out more. 

Can we change Store to Merch as well? Since we don't sell anything besides Merch.

**Comment by pkscout** [comment]
Yes, I can change the Store item title to Merch. I'll also work on the button color for donate.

**Comment by pkscout** [comment]
The update as discussed has been done and pushed to `main`. I'm going to close this.
