### ISSUE TITLE
Contribute page

### ISSUE THREAD

**Issue by Razzeee** [xbmc/kodi-tv#121]
I don't feel like the contribute page works

https://kodi-tv.netlify.app/contribute/

It feels poorly organized and even wastes space. I would propose to move the content to a card list like the lower part of https://kodi-tv.netlify.app/about/

**Comment by pkscout** [comment]
That sounds like a good idea. This is one of the pages where I was originally trying to get it to look like the original page, and we can do better than that.  If we do move it to a set of cards, it's probably better to pull that page from CMS management. The card gallery would be the entire page, so there's no value if having a CMS page that just references a widget you can't edit from the CMS. If we want each card managed from the CMS, we could create a gallery component that is a group of cards and then have the CMS manage the content of each card.

**Comment by Razzeee** [comment]
I don't think that effort is worth the return.

**Comment by pkscout** [comment]
Agreed on not trying to have each card managed in the CMS, but I do think it's worth looking at a card gallery for the sections.   I'll take a look at that later today or tomorrow.

**Comment by pkscout** [comment]
New contribute page is on staging at:

https://kodi-tv-staging.netlify.app/contribute/

I also generalized the FeaturedCard component so that it can be used more places if needed (and moved the Add-on lists to use it).  It does use `prose` and `prose-blue` to render markdown in the body of the card, so the link colors will still be an issue.

The actual contribute index.md page is still CMS managed, mostly just for the opening paragraph.

**Comment by Razzeee** [comment]
Perfect
