### ISSUE TITLE
Section widgets are not styled correctly

### ISSUE THREAD

**Issue by Razzeee** [xbmc/kodi-tv#122]
It seems like section widgets don't inherit the style from above. I think you mentioned that, but I think we should track it. An example would be the about page.

**Comment by pkscout** [comment]
The lack of inheritance is on purpose.  The `prose` class works fine for the text areas, but it is absolutely ugly with anything else.  So the widgets aren't in the same div as the various text sections. In places where we want some amount of consistency, we'll need to figure out what `prose` does for the specific style we want to mimic and then do it by hand.  This might be another place for some named classes that we can reuse.

**Comment by pkscout** [comment]
I think at this point I've cleaned stuff up so that the widgets look OK in the context of the pages. The widgets don't always share the exact same style as the rest of the page, but they do use a pretty common style between them.  I also don't think the necessarily should follow the page style anyway.  I have gotten the links to consistently use the rule "colored kodi and underlined if in a block of text" at least.

This was the really long way of asking if we can close this.
