### ISSUE TITLE
Setup github CI for building

### ISSUE THREAD

**Issue by razzeee** [xbmc/kodi-tv#124]
We should probably make sure that everything builds fine, before it ends up merged. Best way is probably a pipeline build.

**Comment by pkscout** [comment]
Long term I think we'll have enough build minutes to build `staging` at Netlify as well as `main`. Right now what I do is build `staging` locally day to day (and deploy it to Netlify), and then when I'm going to merge into `main` I do one build of `staging` at Netlify to make sure it works. Then I turn off auto builds on `main`, merge, and turn them back on so that the nightly add-on update triggers the new build.  This is all to protect our build minutes but, as I said, I think once we're done with the big chunks of development, we can look at the process.  As for building on Github, I'm not sure that will tell us anything.  I've had some stuff build locally and on Github that didn't on Netlify (mostly around sharp, which I eliminated).

**Comment by Razzeee** [comment]
Interesting, we could at least do a linting/prettier run on CI then. That should be reliable.

**Comment by Razzeee** [comment]
I think we need to work on this.

**Comment by pkscout** [comment]
I did turn on builds for staging and commits against staging at Netlify. That lets you see the site build based on a pull request against staging (even before the pull request is merged). After merge staging is rebuilt as well.  But it isn't validating or checking anything, and I'm not familiar with pipelines.

**Comment by razzeee** [comment]
Has been done
