### ISSUE TITLE
Addon description empty

### ISSUE THREAD

**Issue by Razzeee** [xbmc/kodi-tv#152]
Not sure if that's in the data we get or what the problem is here

https://kodi-tv-staging.netlify.app/addons/matrix/plugin.video.vimeo

**Comment by Razzeee** [comment]
Platforms also can be empty? https://kodi-tv-staging.netlify.app/addons/matrix/plugin.video.themoviedb.helper

**Comment by Razzeee** [comment]
![image](https://user-images.githubusercontent.com/5943908/113487096-50790800-94b6-11eb-83b7-55d12595f6a5.png)

Happens on these elements too, but might be fine to ignore here

**Comment by pkscout** [comment]
It appears Vimeo has a summary but not a description. I can update the addon-parser script so that if there is no description the summary is put in the description. The reason to do that and not just exclude the description is because the "summary" under the add-on name is actually the snippet, and long summaries can get truncated. So even an add-on with only a summary might benefit from having the full summary repeated in the description.

The other ones in that screen shot seem to have neither a description nor a summary in the repo. So there's nothing to show. Interestingly the BBC iPlayer has a description in Matrix, just not in Leia.

Add-ons aren't suppose to have no platforms, but I did run into one at some point that caused a build error, so there is logic to account for that possibility.

**Comment by pkscout** [comment]
The addon-parser script now contains logic to put the summary in the description field if there is no description. If there is no summary nor description, neither field will be included in the JSON file. This allows the Addon Layout component to properly show the description field **only** if there is an actual description.  You won't see the new addon-parser logic in action in staging because I don't like to update the JSON files in staging using the script (it causes commits back to main to have conflicts). So you may still see some addons that have a summary but no description field, at least until next time we merge with main and then pull the updated JSON files back to staging.
