### ISSUE TITLE
Change feed link

### ISSUE THREAD

**Issue by Razzeee** [xbmc/kodi-tv#176]
See if we can change http://feeds.kodi.tv/xbmc to not include xbmc anymore.

@yol

**Comment by yol** [comment]
So this is fixed at feedburner because feeds.kodi.tv is completely under feedburner control and I can't make /xbmc redirect to /kodi. I can add /kodi with the same data though.

Or we get rid of feedburner and let feeds.kodi.tv/xbmc just redirect to the netlify RSS feed.

Thoughts?

PS I deleted http://feeds.feedburner.com/latest_xbmc_addons and http://feeds.feedburner.com/updated_xbmc_addons since they were defunct anyway.

**Comment by Razzeee** [comment]
I think adding the new one in addition to keep it backwards compatible is the right thing to do

**Comment by yol** [comment]
Just tried it.

The uri "kodi" is already taken

So options are now getting rid of feedburner or just not caring - I'm leaning towards the latter. After all, people that already have feeds.kodi.tv/xbmc in their reader are not going to change it anyway. And people that subscribe newly are not going to use feeds.kodi.tv.

**Comment by Razzeee** [comment]
But we're linking to it, so new subscribers will use that too

**Comment by yol** [comment]
Why should we link to it?

**Comment by pkscout** [comment]
There is a link in the footer for the RSS feed, but the only time you'll see it is if you roll over the link or if you click on the link and actually look at the URL bar (assuming your browser is even showing you the full URL, which many don't by default). I'd put this is the "don't worry about it category" because it seems like any fix we try ends up breaking the current feed. And that's worse than having xbmc in the URL in my opinion.

**Comment by pkscout** [comment]
I can live with that.  I'll revert the footer so that it's pointing to /rss.xml.  The good news is that I'm subscribed to the feedburner feed, so if we have any issue with the historical feedburner stuff, I'll know very early.

**Comment by pkscout** [comment]
Changed footer back to linking directly to the RSS feed instead of Feedburner with ed8624a9b49e35e07cc81b18d0dca0e960ccba71.
