### ISSUE TITLE
Page titles

### ISSUE THREAD

**Issue by yol** [xbmc/kodi-tv#185]
Right now, the page titles look like this:

Kodi | Open Source Home Theater Software | Addons | Matrix | Sublissimo

I think it should be the other way around - the most specific information should come in front so you can identify tabs if you have lots of them open. As it stands, everything after Open Source... will just be cut off.

What do you think?

**Comment by Razzeee** [comment]
Sure, maybe we can even loose the `Open Source Home Theater Software`? 

The favicon should be enough to figure out it's kodi.

**Comment by pkscout** [comment]
I'm not a big fan of reversing the page title from a readability perspective. I think it should read logically left to right. But we could certainly cut out the open source part (maybe have that only on the home page). I'd keep the Kodi part just because I'd like saved bookmarks to have the Kodi name in them for identification purposes.

**Comment by pkscout** [comment]
OK, I gave in.  I've reversed all the page title info and removed the "Open Source Home Theater Software" item (except on the home page).  It's in staging for testing (or at least it will be in about 10 minutes).

**Comment by pkscout** [comment]
Fixed with c1781e1ee452a33ece53bd40102a05006f215769 back in November.  Closing.
