### ISSUE TITLE
Run lighthouse test and improve SEO

### ISSUE THREAD

**Issue by Razzeee** [xbmc/kodi-tv#33]

**Comment by pkscout** [comment]
Here's a way to do that locally.

https://www.gatsbyjs.com/docs/audit-with-lighthouse/

**Comment by Razzeee** [comment]
Did some first tests, it seems like most work will be images.

Other then that, I started with https://github.com/xbmc/kodi-tv/pull/112

**Comment by pkscout** [comment]
Yea, I noticed that too.  I'd like to use some of the Gatsby tools for images but (a) they seem to require a good deal of work and a bunch of round tripping through GraphQL and (b) if anything requires gatsby-plugin-sharp we are currently out of luck. I can only rarely get sharp to build on my development machine (macOS), and I have **never** been able to get sharp to build at Netlify (I really should submit a ticket about that). That also means we have to use a more manual way of doing the favicon (instead of using gatsby-manifest to build the icon sizes, since that requires sharp).

**Comment by Razzeee** [comment]
Seems happier now 
![image](https://user-images.githubusercontent.com/5943908/112749312-df22ec00-8fc1-11eb-8763-c117af9747aa.png)

but I think I will try to get sharp going too. Let's see what happens.

**Comment by Razzeee** [comment]
Not too sure about some of the contrast, might have to change colors slightly, just a reminder

**Comment by pkscout** [comment]
Are there other things we need to check on this issue, or can it be closed?

**Comment by Razzeee** [comment]
I think it's fine to close, I might run it again anyway, at some point.
