### ISSUE TITLE
Blog Posts: Possible to have Categories or Tags, perhaps searchable?

### ISSUE THREAD

**Issue by ProfYaffle** [xbmc/kodi-tv#57]
It seems that all blog posts are dumped into the same Collection at the moment. That means that the _News_ section of the web site is just one, long, chronological list of posts.

There's currently no way to group/filter them (e.g. "_Release Announcements_" or "_DevCon_"), nor is there seemingly any way to search them based on topic, content, date, or anything else.

I suspect the former could be handled through a tag plugin or perhaps the _config.yml_, although this sounds like a fraught way to add or maintain categories, and likely to screw up at some point. The latter then sounds like some changes needed to the _News_ pages, so probably wanders off into Gatsby territory.

**Comment by pkscout** [comment]
We can look at search.  There appear to be two Netlify "approved" methods. One that's free and will take some work, and one that likely costs money and will maybe take less work.

Free option: https://github.com/sw-yx/netlify-plugin-search-index#readme
Possible pay option: https://github.com/algolia/algoliasearch-netlify#readme

On the tags side, I can update the config.yml to add the ability to tag blog posts, and this appears to be the best (or at least by far the most common) way to deal with tagging blog posts and then create some more page templates.  It does mean we should probably agree on a smallish set of tags and not update the list of tags all the time.  The current site has 44 different tags, many of them have zero or one entries, a few have maybe half a dozen entries, and a small number (like Release Announcements) have a pretty decent amount of content.  Since the blog really should be just for news related items now (at one point it looks like it was trying to be a documentation repository too), I am hopeful we can come up with maybe a half dozen really useful tags.

With sites like Drupal and Wordpress, tags cost, in essence, nothing. Add them, tag content with them, get lists of results. But with pagebuilders, tags cost something (in build time).  A half a dozen tags means a half a dozen new pages to build. 44 tags means 44 new pages to build.  That's why I'd probably a small number of useful, relevant tags rather than 44 tags that we have "just because."

I'll start working on the CMS and Gatsby changes to do tags while we figure out exactly what tags we really want/need.

**Comment by pkscout** [comment]
Tags have been implemented in both the CMS and the site pages now. You can see them in action at:

https://kodi-tv.netlify.app

I picked a few tags I thought we might used and tagged a few blog posts just so you could see what it looked life.  As an FYI, the list of tags on the right side of the blog page will only show tags that have actually been used.  So the list you see in the CMS is longer than what's on the site.  Assuming we go this route, this is another instance will editing the markdown files of the blog posts to add back tags will probably be a better idea than doing it in the CMS. But we could do it in the CMS. I would just want to disable automatic build while you do it, unless we really want to test the buildbot to see if it stops building if it gets lots of build requests in a row.  '-)

**Comment by pkscout** [comment]
Tags are much prettier in the new Tailwind based UI. Still need to do some research on search.

**Comment by pkscout** [comment]
There is a search function now available in staging at: https://kodi-tv-staging.netlify.app/blog (click on the link called ADVANCED SEARCH in the Tag sidebar).  It's somewhat rudimentary, and at some point I'd like to implement a fuzzy search instead, but it should do to get us started.  Since this issue also includes the tags (that we need to finalize and assign to posts at some point), I'm leaving this open but moving it to "needs testing."

**Comment by pkscout** [comment]
Search is now available on the main site at https://kodi-tv.netlify.app.
