### ISSUE TITLE
Download page- reorganise icons

### ISSUE THREAD

**Issue by KarellenX** [xbmc/kodi-tv#6]
Is it possible to reorganise the platform icons in the Download page.

We have 6 icons on the first row, and a single lonely icon on the second row.

Maybe group the Apple platforms as there are a few of them. Something like in the following image...

![downloads](https://user-images.githubusercontent.com/44626605/101563778-01e2c200-3a1e-11eb-8530-5c911504060e.jpg)

**Comment by pkscout** [comment]
I'm going to keep looking at this, but it may require some more CSS fu than I have. The challenge is that we **want** to have the list wrap as the screen size changes so that it looks good on mobile and desktop. And that means there will be some screen sizes from time to time where there is one lone icon on a row. If we split them into two groups (the first four and the Apple ones), then as we wrap we could end up with one from the first group on one row by itself (so basically three rows of 3, 1, and 3 items). That would be worse.

The funny part is that your suggested layout is exactly what I see already on my laptop screen.

**Comment by nlok5923** [comment]
@KarellenX  can i work on this issue.

**Comment by pkscout** [comment]
We're in process of moving everything from PatternFly to TailwindCSS for layout and display. It may be that we can better address that then, and any fix you make to the PatternFly layout will end up not mattering anyway.  I welcome the help, but maybe not right this second.  '-)

**Comment by pkscout** [comment]
This has been resolved as part of the Tailwind UI migration. The icons now do a 4 item then three item row on larger screens and change as needed with smaller screens.
